import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PathnameProvider from "@/components/common/PathnameProvider";
import PublicLayout from "@/components/layout/PublicLayout";
import AuthProvider from "@/components/common/AuthProvider";
import PrivateHeader from "@/components/layout/PrivateHeader";
import Sidebar from "@/components/layout/Sidebar";
import AuthLayout from "@/components/layout/AuthLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PathnameProvider>
            <AuthLayout>{children}</AuthLayout>{" "}
            {/* ✅ Pass children normally */}
          </PathnameProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
